from __future__ import annotations
REPORT_LABELS = {
    "fr": {
        "report_title": "Rapport Candidat",
        "report_subtitle": "Evaluation technique contextualisee",
        "candidate_fallback": "Candidat",
        "profile_fallback": "Profil non precise",
        "session": "Session",
        "date": "Date",
        "overall_score": "Score global",
        "score_caption": "Moyenne des competences observees",
        "profile_overview": "Apercu entretien",
        "questions_handled": "Questions traitees",
        "stacks_skills": "Stacks / competences",
        "stacks_fallback": "Non precise",
        "observed_competencies": "Competences observees",
        "question_grades": "Notes par question",
        "question_fallback": "Question",
        "technical_review": "Lecture technique",
        "strengths": "Points forts",
        "improvements": "Points a approfondir",
        "advice": "Conseils pour le candidat",
        "summary": "Synthese",
        "balanced_profile": "Profil globalement equilibre",
        "progress_axes": "Axes de progression a confirmer",
        "advice_fallback": "Structurer les reponses avec des exemples concrets et mesurables",
        "summary_fallback": "Resume non disponible.",
        "score_labels": {
            "strong": "Solide",
            "correct": "Correct",
            "improve": "A approfondir",
            "confirm": "A confirmer",
        },
        "competencies": {
            "question_score": "Note des reponses",
        },
        "insights_report_title": "Insights Visuels & Vocaux",
        "insights_report_subtitle": "Synthese des signaux visuels, vocaux et du stress observe",
        "insights_overview": "Apercu global",
        "visual_score": "Lecture visuelle",
        "audio_score": "Lecture vocale",
        "stress_score": "Stress observe",
        "average_caption": "Indicateur moyen",
        "stress_caption": "Lecture indicative",
        "insights_highlights": "Insights automatises",
        "visual_signals_title": "Signaux visuels",
        "audio_signals_title": "Signaux vocaux",
        "stress_summary_title": "Synthese stress",
        "visual_metrics_title": "Metriques visuelles",
        "audio_metrics_title": "Metriques vocales",
        "emotion_breakdown_title": "Repartition emotionnelle",
        "no_visual_signal": "Aucun signal visuel notable n'a ete capture.",
        "no_audio_signal": "Aucun signal vocal notable n'a ete capture.",
        "stress_fallback": "Lecture du stress indisponible.",
        "insights_fallback": "Aucun insight automatique supplementaire n'est disponible.",
        "metrics_fallback": "Mesures non disponibles.",
        "emotion_fallback": "Aucune emotion dominante detectee.",
        "confidence_note": "Note de confiance",
        "face_detected": "Face detectee",
        "centering": "Centrage",
        "stable_posture": "Posture stable",
        "visual_engagement": "Engagement visuel",
        "speech_rate": "Debit",
        "volume": "Volume",
        "useful_silence": "Silence utile",
        "variation": "Variation",
        "emotion_labels": {
            "happy": "Happy",
            "angry": "Angry",
            "sad": "Sad",
            "neutral": "Neutral",
            "surprise": "Surprise",
        },
    },
    "en": {
        "report_title": "Candidate Report",
        "report_subtitle": "Contextualized Technical Evaluation",
        "candidate_fallback": "Candidate",
        "profile_fallback": "Profile not specified",
        "session": "Session",
        "date": "Date",
        "overall_score": "Overall Score",
        "score_caption": "Average observed competencies",
        "profile_overview": "Interview snapshot",
        "questions_handled": "Questions covered",
        "stacks_skills": "Stacks / skills",
        "stacks_fallback": "Not specified",
        "observed_competencies": "Observed Competencies",
        "question_grades": "Grades by question",
        "question_fallback": "Question",
        "technical_review": "Technical Review",
        "strengths": "Strengths",
        "improvements": "Areas to explore",
        "advice": "Advice for the Candidate",
        "summary": "Summary",
        "balanced_profile": "Overall balanced profile",
        "progress_axes": "Areas for improvement to confirm",
        "advice_fallback": "Structure answers with concrete, measurable examples",
        "summary_fallback": "Summary unavailable.",
        "score_labels": {
            "strong": "Strong",
            "correct": "Correct",
            "improve": "Needs improvement",
            "confirm": "To confirm",
        },
        "competencies": {
            "question_score": "Answer grade",
        },
        "insights_report_title": "Visual & Vocal Insights",
        "insights_report_subtitle": "Summary of visual, vocal, and observed stress signals",
        "insights_overview": "Global overview",
        "visual_score": "Visual reading",
        "audio_score": "Vocal reading",
        "stress_score": "Observed stress",
        "average_caption": "Average indicator",
        "stress_caption": "Indicative reading",
        "insights_highlights": "Automated insights",
        "visual_signals_title": "Visual signals",
        "audio_signals_title": "Vocal signals",
        "stress_summary_title": "Stress summary",
        "visual_metrics_title": "Visual metrics",
        "audio_metrics_title": "Vocal metrics",
        "emotion_breakdown_title": "Emotion breakdown",
        "no_visual_signal": "No notable visual signal was captured.",
        "no_audio_signal": "No notable vocal signal was captured.",
        "stress_fallback": "Stress reading unavailable.",
        "insights_fallback": "No additional automated insight is available.",
        "metrics_fallback": "Metrics unavailable.",
        "emotion_fallback": "No dominant emotion detected.",
        "confidence_note": "Confidence note",
        "face_detected": "Face detected",
        "centering": "Centering",
        "stable_posture": "Stable posture",
        "visual_engagement": "Visual engagement",
        "speech_rate": "Speech rate",
        "volume": "Volume",
        "useful_silence": "Useful silence",
        "variation": "Variation",
        "emotion_labels": {
            "happy": "Happy",
            "angry": "Angry",
            "sad": "Sad",
            "neutral": "Neutral",
            "surprise": "Surprise",
        },
    },
}
