.venv
venv
env
__pycache__
**/__pycache__
*.pyc
*.pyo
*.pyd
.Python

data/*
!data/models/
!data/models/emotion/
!data/models/emotion/efficientnet_b3_20260425_053142/
!data/models/emotion/efficientnet_b3_20260425_053142/**
*.sqlite
*.db
*.log

.pytest_cache
.mypy_cache
.ruff_cache
htmlcov
coverage

tests
test_*.py
*-report.html

.env
.env.*
.deployment
appsvc.yaml
README.md
